# Generated by Django 5.1.2 on 2024-11-16 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
