# Generated by Django 5.1.2 on 2024-11-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_product_color_remove_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="product.color"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="product.size"
            ),
        ),
    ]
